using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using System.IO;
using System.Threading;
using System.Linq;
using System;


namespace QarnotSDK {

    /// <summary>
    /// This class manages pools life cycle: submission, monitor, delete.
    /// </summary>
    public abstract partial class AQPool {

        /// <summary>
        /// Reference to the api connection.
        /// </summary>
        protected Connection _api;

        /// <summary>
        /// The pool resource uri.
        /// </summary>
        protected string _uri = null;

        internal PoolApi _poolApi { get; set; }

        /// <summary>
        /// The inner Connection object.
        /// </summary>
        public Connection Connection { get { return _api; } }

        /// <summary>
        /// The pool unique identifier. The Uuid is generated by the Api when the pool is submitted.
        /// </summary>
        public Guid Uuid { get { return _poolApi.Uuid; } }

        internal AQPool() { }

        internal AQPool(Connection qapi, PoolApi poolApi) {
            _api = qapi;
            _uri = "pools/" + poolApi.Uuid.ToString();
            _poolApi = poolApi;
        }

        internal virtual async Task<AQPool> InitializeAsync(Connection qapi, PoolApi poolApi) {
            _api = qapi;
            _uri = "pools/" + poolApi.Uuid.ToString();
            _poolApi = poolApi;
            return this;
        }

        #region public methods
        /// <summary>
        /// Delete the pool.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        [Obsolete("use CloseAsync")]
        public async Task StopAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            if (_api.IsReadOnly) throw new Exception("Can't stop pools, this connection is configured in read-only mode");
            var response = await _api._client.DeleteAsync(_uri, cancellationToken);
            await Utils.LookForErrorAndThrowAsync(_api._client, response);
        }

        /// <summary>
        /// Close the pool.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public async Task CloseAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            if (_api.IsReadOnly) throw new Exception("Can't close pools, this connection is configured in read-only mode");
            var response = await _api._client.PostAsync(_uri + "/close", null, cancellationToken);
            await Utils.LookForErrorAndThrowAsync(_api._client, response);
        }

        /// <summary>
        /// Delete the pool. If the pool is running, the pool is closed and deleted.
        /// </summary>
        /// <param name="failIfDoesntExist">If set to true and the pool doesn't exist, an exception is thrown. Default is false.</param>
        /// <returns></returns>
        public async Task DeleteAsync(bool failIfDoesntExist = false) {
            await DeleteAsync(default(CancellationToken), failIfDoesntExist);
        }

        /// <summary>
        /// Delete the pool. If the pool is running, the pool is closed and deleted.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <param name="failIfDoesntExist">If set to false and the pool doesn't exist, no exception is thrown. Default is true.</param>
        /// <returns></returns>
        public async Task DeleteAsync(CancellationToken cancellationToken, bool failIfDoesntExist = false) {
            try {
                if (_api.IsReadOnly) throw new Exception("Can't delete pools, this connection is configured in read-only mode");
                var response = await _api._client.DeleteAsync(_uri, cancellationToken);

                await Utils.LookForErrorAndThrowAsync(_api._client, response);
            } catch (QarnotApiResourceNotFoundException ex) {
                if (failIfDoesntExist) throw ex;
            }
        }
        #endregion
    }
}
