using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using System.IO;
using System.Threading;
using System.Linq;
using System;


namespace QarnotSDK {

    /// <summary>
    /// This class manges tasks life cycle: submission, monitor, delete.
    /// </summary>
    public abstract partial class AQTask {

        /// <summary>
        /// Reference to the api connection.
        /// </summary>
        protected Connection _api;

        /// <summary>
        /// The task resource uri.
        /// </summary>
        protected string _uri = null;

        internal TaskApi _taskApi { get; set; }

        /// <summary>
        /// The inner Connection object.
        /// </summary>
        [InternalDataApiName(IsFilterable=false, IsSelectable=false)]
        public  virtual Connection Connection { get { return _api; } }

        /// <summary>
        /// The task unique identifier. The Uuid is generated by the Api when the task is submitted.
        /// </summary>
        [InternalDataApiName(Name="Uuid")]
        public virtual Guid Uuid { get { return _taskApi.Uuid; } }

        internal AQTask() { }

        internal AQTask(Connection qapi, TaskApi taskApi) {
            _api = qapi;
            _uri = "tasks/" + taskApi.Uuid.ToString();
            _taskApi = taskApi;
        }

        internal virtual async Task<AQTask> InitializeAsync(Connection qapi, TaskApi taskApi) {
            _api = qapi;
            _uri = "tasks/" + taskApi.Uuid.ToString();
            _taskApi = taskApi;
            return await Task.FromResult(this);
        }

        #region public methods
        /// <summary>
        /// Abort a running task.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task AbortAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            if (_api.IsReadOnly) throw new Exception("Can't abort tasks, this connection is configured in read-only mode");
            using (var response = await _api._client.PostAsync(_uri + "/abort", null, cancellationToken))
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
        }

        /// <summary>
        /// Delete the task. If the task is running, the task is aborted and deleted.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <param name="failIfDoesntExist">If set to false and the task doesn't exist, no exception is thrown. Default is true.</param>
        /// <param name="purgeResources">Boolean to trigger all resource storages deletion. Default is false.</param>
        /// <param name="purgeResults">Boolean to trigger result storage deletion. Default is false.</param>
        /// <returns></returns>
        public abstract Task DeleteAsync(CancellationToken cancellationToken,
            bool failIfDoesntExist = false, bool purgeResources=false, bool purgeResults=false);

        /// <summary>
        /// Delete the task. If the task is running, the task is aborted and deleted.
        /// </summary>
        /// <param name="failIfDoesntExist">If set to false and the task doesn't exist, no exception is thrown. Default is true.</param>
        /// <param name="purgeResources">Boolean to trigger all resource storages deletion. Default is false.</param>
        /// <param name="purgeResults">Boolean to trigger result storage deletion. Default is false.</param>
        /// <returns></returns>
        public virtual async Task DeleteAsync(bool failIfDoesntExist = false, bool purgeResources=false, bool purgeResults=false)
            => await DeleteAsync(default(CancellationToken), failIfDoesntExist, purgeResources, purgeResults);
        #endregion

        #region resource updates/snapshots
        /// <summary>
        /// Request made on a running task to re-sync the resource buckets to the compute nodes.
        ///  1 - Upload new files on your resource bucket,
        ///  2 - Call this method,
        ///  3 - The new files will appear on all the compute nodes in the $DOCKER_WORKDIR folder
        /// Note: There is no way to know when the files are effectively transfered. This information is available on the compute node only.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task UpdateResourcesAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            if (_api.IsReadOnly) throw new Exception("Can't update resources, this connection is configured in read-only mode");
            var reqMsg = new HttpRequestMessage(new HttpMethod("PATCH"), _uri);
            using (var response = await _api._client.SendAsync(reqMsg, cancellationToken))
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
        }

        /// <summary>
        /// Request made on a running task to sync the result files in $DOCKER_WORKDIR on the compute node to the result bucket.
        /// Note: There is no way to know when all the results are effectively transfered. This information is available by monitoring the
        /// task ResultsCount or by checking the result bucket.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task SnapshotAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            if (_api.IsReadOnly) throw new Exception("Can't request a snapshot, this connection is configured in read-only mode");
            using (var response = await _api._client.PostAsync(_uri + "/snapshot", null, cancellationToken))
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
        }

        /// <summary>
        /// Start a periodic snapshotting of the results.
        /// </summary>
        /// <param name="interval">Interval in seconds between two snapshots.</param>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task SnapshotPeriodicAsync(uint interval, CancellationToken cancellationToken = default(CancellationToken)) {
            Snapshot s = new QarnotSDK.Snapshot();
            s.Interval = Convert.ToInt32(interval);
            if (_api.IsReadOnly) throw new Exception("Can't configure snapshots, this connection is configured in read-only mode");
            using (var response = await _api._client.PostAsJsonAsync<Snapshot>(_uri + "/snapshot/periodic", s))
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
        }
        #endregion


        #region stdin/stdout
        /// <summary>
        /// Copies the full standard output to the given stream.
        /// Note: the standard output will rotate if it's too large.
        /// </summary>
        /// <param name="destinationStream">The destination stream.</param>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task CopyStdoutToAsync(Stream destinationStream, CancellationToken cancellationToken = default(CancellationToken)) {
            using (var response = await _api._client.GetAsync(_uri + "/stdout", cancellationToken))
            {
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
                await response.Content.CopyToAsync(destinationStream);
            }
        }

        /// <summary>
        /// Copies the full standard error to the given stream.
        /// Note: the standard error will rotate if it's too large.
        /// </summary>
        /// <param name="destinationStream">The destination stream.</param>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task CopyStderrToAsync(Stream destinationStream, CancellationToken cancellationToken = default(CancellationToken)) {
            using (var response = await _api._client.GetAsync(_uri + "/stderr", cancellationToken))
            {
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
                await response.Content.CopyToAsync(destinationStream);
            }
        }

        /// <summary>
        /// Copies the fresh new standard output since the last call to the given stream.
        /// </summary>
        /// <param name="destinationStream">The destination stream.</param>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task CopyFreshStdoutToAsync(Stream destinationStream, CancellationToken cancellationToken = default(CancellationToken)) {
            if (_api.IsReadOnly) throw new Exception("Can't retrieve fresh standard output, this connection is configured in read-only mode");
            using (var response = await _api._client.PostAsync(_uri + "/stdout", null, cancellationToken))
            {
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
                await response.Content.CopyToAsync(destinationStream);
            }
        }

        /// <summary>
        /// Copies the fresh new standard error since the last call to the given stream.
        /// </summary>
        /// <param name="destinationStream">The destination stream.</param>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns></returns>
        public virtual async Task CopyFreshStderrToAsync(Stream destinationStream, CancellationToken cancellationToken = default(CancellationToken)) {
            if (_api.IsReadOnly) throw new Exception("Can't retrieve fresh standard error, this connection is configured in read-only mode");
            using (var response = await _api._client.PostAsync(_uri + "/stderr", null, cancellationToken))
            {
                await Utils.LookForErrorAndThrowAsync(_api._client, response);
                await response.Content.CopyToAsync(destinationStream);
            }
        }

        /// <summary>
        /// Returns the full standard output.
        /// Note: the standard output will rotate if it's too large.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns>The task standard output.</returns>
        public virtual async Task<string> StdoutAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            using (MemoryStream ms = new MemoryStream()) {
                await CopyStdoutToAsync(ms, cancellationToken);
                ms.Position = 0;
                using (var reader = new StreamReader(ms)) {
                    return await reader.ReadToEndAsync();
                }
            }
        }

        /// <summary>
        /// Return the full standard error.
        /// Note: the standard error will rotate if it's too large.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns>The task standard error.</returns>
        public virtual async Task<string> StderrAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            using (MemoryStream ms = new MemoryStream()) {
                await CopyStderrToAsync(ms, cancellationToken);
                ms.Position = 0;
                using (var reader = new StreamReader(ms)) {
                    return await reader.ReadToEndAsync();
                }
            }
        }

        /// <summary>
        /// Returns the fresh new standard output since the last call.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns>The task fresh standard output.</returns>
        public virtual async Task<string> FreshStdoutAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            using (MemoryStream ms = new MemoryStream()) {
                await CopyFreshStdoutToAsync(ms, cancellationToken);
                ms.Position = 0;
                using (var reader = new StreamReader(ms)) {
                    return await reader.ReadToEndAsync();
                }
            }
        }

        /// <summary>
        /// Returns the fresh new standard error since the last call.
        /// </summary>
        /// <param name="cancellationToken">Optional token to cancel the request.</param>
        /// <returns>The task fresh standard error.</returns>
        public virtual async Task<string> FreshStderrAsync(CancellationToken cancellationToken = default(CancellationToken)) {
            using (MemoryStream ms = new MemoryStream()) {
                await CopyFreshStderrToAsync(ms, cancellationToken);
                ms.Position = 0;
                using (var reader = new StreamReader(ms)) {
                    return await reader.ReadToEndAsync();
                }
            }
        }
        #endregion
    }
}
