using Newtonsoft.Json;

namespace QarnotSDK.Sdk
{
    /// <summary>
    /// Carbon facts details of a computed element
    /// </summary>
    public class CarbonFacts
    {
        /// <summary>
        /// The total energy consumed by the execution (in Watt hour)
        /// </summary>
        [JsonProperty("total_consumed_energy_Wh")]
        public double TotalConsumedEnergyWh { get; set; }

        /// <summary>
        /// The total energy consumed by the infrastructure IT during execution (in Watt hour)
        /// </summary>
        [JsonProperty("total_energy_it_Wh")]
        public double TotalEnergyITWh { get; set; }

        /// <summary>
        /// The total energy reused by the site from the computation (in Watt hour)
        /// </summary>
        [JsonProperty("total_reused_energy_Wh")]
        public double TotalReuseEnergyWh { get; set; }


        /// <summary>
        /// The carbon footprint generated by the computation (in gCO2eq)
        /// </summary>
        [JsonProperty("qarnot_carbon_footprint")]
        public double CarbonFootprint_gCO2Eq { get; set; }

        /// <summary>
        /// The name of the equivalent data center used for comparison
        /// </summary>
        [JsonProperty("equivalent_datacenter_name")]
        public string EquivalentDataCenterName { get; set; }

        /// <summary>
        /// The carbon footprint the computation would have generated in the equivalent data center
        /// <see cref="EquivalentDataCenterName"/> (in gCO2eq)
        /// </summary>
        [JsonProperty("equivalent_DC_carbon_footprint")]
        public double EquivalentDCCarbonFootprint_gCO2Eq { get; set; }

        /// <summary>
        /// The carbon footprint saved by the computation in Qarnot compared to the theoretical computation
        /// in the equivalent data center <see cref="EquivalentDataCenterName"/>  (in gCO2eq)
        /// </summary>
        [JsonProperty("saved_carbon_footprint_compute")]
        public double SavedCarbonFootprintCompute_gCO2Eq { get; set; }

        /// <summary>
        /// The carbon footprint saved by the heating using computation in Qarnot (in gCO2eq)
        /// </summary>
        [JsonProperty("saved_carbon_footprint_heat")]
        public double SavedCarbonFootprintHeat_gCO2Eq { get; set; }

        /// <summary>
        /// The carbon footprint saved from both compute and heat parts
        /// </summary>
        [JsonProperty("saved_carbon_footprint_compute_heat")]
        public double SavedCarbonFootprintComputeHeat_gCO2Eq { get; set; }

        /// <summary>
        /// The percentage of carbon footprint saved
        /// </summary>
        [JsonProperty("saved_carbon_footprint_percent")]
        public double SavedCarbonFootprintPercentage { get; set; } // %


        /// <summary>
        /// The Power Usage Effectiveness of the computation by Qarnot infrastructure
        /// It represents the total consumed energy divided by the part consumed by IT
        /// The value varies between 1 and 2.
        /// The more the PUE is near 1, the more the energy is effectively consumed.
        /// </summary>
        [JsonProperty("PUE")]
        public decimal? PUE { get; set; }

        /// <summary>
        /// The Energy Reuse Effectiveness of the computation by Qarnot infrastructure
        /// It represents the consumed energy without the energy reused divided by the part consumed by IT
        /// The value varies between 0 and 2.
        /// The more the ERE is near 0, the more energy is effectively reused.
        /// </summary>
        [JsonProperty("ERE")]
        public decimal? ERE { get; set; }

        /// <summary>
        /// The Energy Reuse Factor of the computation by Qarnot infrastructure
        /// It represents the reused energy divided by the total energy consumed
        /// The value varies between 0 and 1.
        /// The more the ERF is near 1, the more energy is reused.
        /// </summary>
        [JsonProperty("ERF")]
        public decimal? ERF { get; set; }

        /// <summary>
        /// The Water Usage Effectiveness of the computation by Qarnot infrastructure
        /// It represents the total consumed water divided by the energy consumed by IT
        /// The more the WUE is near 0, the less water is spoiled.
        /// </summary>
        [JsonProperty("WUE")]
        public decimal? WUE { get; set; } // L/kWh

    }
}